site_name: Zebbra Docs

nav:
  - Start: index.md
  - MkDocs Configuration: mkdocs.md
  - Dummy Project: '!import https://github.com/zebbra/zebbra-mkdocs-dummyproject?branch=main&extra_imports=["src/*", "dummyproject-src"]'

# --8<-- [start:theme]
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.share
    - search.suggest
    - search.highlight
    - content.action.edit

  # Dark and light mode, defaults to system theme
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
# --8<-- [end:theme]

# --8<-- [start:markdown_extensions]
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
      # https://github.com/mkdocs/mkdocs/issues/2154
      base_path:
        - "mkdocs.yml"
        - "."
        - "temp_dir/dummy-project"
# --8<-- [end:markdown_extensions]

# --8<-- [start:plugins]
plugins:
  # Enables search
  - search
  # Enables export as PDF
  # - pdf-export
  # Allows to add a whole directory in the navigation instead of just files
  # Sub-nav items are automatically created if the provided dir contains subdirectories
  - include_dir_to_nav
  # Include content of other files in markdown
  - include-markdown:
      encoding: ascii
      preserve_includer_indent: false
      dedent: false
      trailing_newlines: true
      comments: true
      rewrite_relative_urls: true # true is default
      heading_offset: 0
      opening_tag: "{%"
      closing_tag: "%}"
      start: <!--start-->
      end: <!--end-->
  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: false
      # if set the docs directory will not be removed when importing docs.
      # When using this with a nav section in an imported repo you must keep the
      # docs directory in the path (e.g., docs/path/to/file.md).
      keep_docs_dir: false
# --8<-- [end:plugins]

# --8<-- [start:repo]
repo_url: https://github.com/zebbra/zebbra-mkdocs
edit_uri: edit/main/docs
# --8<-- [end:repo]

# --8<-- [start:social]
extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://neops.io
      name: Neops
# --8<-- [end:social]

# --8<-- [start:copyright]
copyright: Copyright &copy; Zebbra AG
# --8<-- [end:copyright]